// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUYb1CIk_9GUt7wy4CNImrlbit-Jqnj6Q',
    appId: '1:301952263004:web:756f82633a135a3df75799',
    messagingSenderId: '301952263004',
    projectId: 'neocaresmileapp-prod',
    authDomain: 'neocaresmileapp-prod.firebaseapp.com',
    storageBucket: 'neocaresmileapp-prod.appspot.com',
    measurementId: 'G-SVG8KYJYC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEvOxyhcCKRU4YUUvMIYqOavsUGcJmW4k',
    appId: '1:301952263004:android:270e18bf507343c2f75799',
    messagingSenderId: '301952263004',
    projectId: 'neocaresmileapp-prod',
    storageBucket: 'neocaresmileapp-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUiV9yBHhmEbHyZ783vx6viH8UK8w7Eoc',
    appId: '1:301952263004:ios:d4dbb43265bae44af75799',
    messagingSenderId: '301952263004',
    projectId: 'neocaresmileapp-prod',
    storageBucket: 'neocaresmileapp-prod.appspot.com',
    iosBundleId: 'com.example.neocaresmileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUiV9yBHhmEbHyZ783vx6viH8UK8w7Eoc',
    appId: '1:301952263004:ios:d4dbb43265bae44af75799',
    messagingSenderId: '301952263004',
    projectId: 'neocaresmileapp-prod',
    storageBucket: 'neocaresmileapp-prod.appspot.com',
    iosBundleId: 'com.example.neocaresmileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUYb1CIk_9GUt7wy4CNImrlbit-Jqnj6Q',
    appId: '1:301952263004:web:b9e0ab8f370b65ecf75799',
    messagingSenderId: '301952263004',
    projectId: 'neocaresmileapp-prod',
    authDomain: 'neocaresmileapp-prod.firebaseapp.com',
    storageBucket: 'neocaresmileapp-prod.appspot.com',
    measurementId: 'G-Z5L90CKQWQ',
  );
}
