// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStaging {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8h7pvgWtV8JCoc6bQw0vsLugxK6XOEnY',
    appId: '1:295848318344:web:16a2e128369bbb8f46563d',
    messagingSenderId: '295848318344',
    projectId: 'neocaresmileapp-staging-9cfe7',
    authDomain: 'neocaresmileapp-staging-9cfe7.firebaseapp.com',
    storageBucket: 'neocaresmileapp-staging-9cfe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7jq2QQyaMy1nxfGys2KCvblCb0KePGIM',
    appId: '1:295848318344:ios:fb793de479f2f9f746563d',
    messagingSenderId: '295848318344',
    projectId: 'neocaresmileapp-staging-9cfe7',
    storageBucket: 'neocaresmileapp-staging-9cfe7.firebasestorage.app',
    iosBundleId: 'com.example.neocaresmileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7jq2QQyaMy1nxfGys2KCvblCb0KePGIM',
    appId: '1:295848318344:ios:fb793de479f2f9f746563d',
    messagingSenderId: '295848318344',
    projectId: 'neocaresmileapp-staging-9cfe7',
    storageBucket: 'neocaresmileapp-staging-9cfe7.firebasestorage.app',
    iosBundleId: 'com.example.neocaresmileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8h7pvgWtV8JCoc6bQw0vsLugxK6XOEnY',
    appId: '1:295848318344:web:5b79e658c3044cf646563d',
    messagingSenderId: '295848318344',
    projectId: 'neocaresmileapp-staging-9cfe7',
    authDomain: 'neocaresmileapp-staging-9cfe7.firebaseapp.com',
    storageBucket: 'neocaresmileapp-staging-9cfe7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDucGS7xGTwEtdIvPg9-gDLqEBbYlRjI5A',
    appId: '1:295848318344:android:26c06dcab861af0b46563d',
    messagingSenderId: '295848318344',
    projectId: 'neocaresmileapp-staging-9cfe7',
    storageBucket: 'neocaresmileapp-staging-9cfe7.firebasestorage.app',
  );
}
