// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ8pZFbqJw2M571iEVx84gFvTbVE5ywBM',
    appId: '1:589102946015:web:e1c5eac6559e085989bb6a',
    messagingSenderId: '589102946015',
    projectId: 'neocaresmileapp-prod-d6930',
    authDomain: 'neocaresmileapp-prod-d6930.firebaseapp.com',
    storageBucket: 'neocaresmileapp-prod-d6930.firebasestorage.app',
    measurementId: 'G-HJSDLL7P76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwu6eA2yHUEETD8kO10-9dhOyxh2o6rxQ',
    appId: '1:589102946015:android:17f6b80dadc28a2d89bb6a',
    messagingSenderId: '589102946015',
    projectId: 'neocaresmileapp-prod-d6930',
    storageBucket: 'neocaresmileapp-prod-d6930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZWl9wEa00RrYATLPXNijFA1kAGIzYmP0',
    appId: '1:589102946015:ios:c04a879afb02f44389bb6a',
    messagingSenderId: '589102946015',
    projectId: 'neocaresmileapp-prod-d6930',
    storageBucket: 'neocaresmileapp-prod-d6930.firebasestorage.app',
    iosBundleId: 'com.example.neocaresmileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZWl9wEa00RrYATLPXNijFA1kAGIzYmP0',
    appId: '1:589102946015:ios:c04a879afb02f44389bb6a',
    messagingSenderId: '589102946015',
    projectId: 'neocaresmileapp-prod-d6930',
    storageBucket: 'neocaresmileapp-prod-d6930.firebasestorage.app',
    iosBundleId: 'com.example.neocaresmileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ8pZFbqJw2M571iEVx84gFvTbVE5ywBM',
    appId: '1:589102946015:web:f9671650ba9ccd7389bb6a',
    messagingSenderId: '589102946015',
    projectId: 'neocaresmileapp-prod-d6930',
    authDomain: 'neocaresmileapp-prod-d6930.firebaseapp.com',
    storageBucket: 'neocaresmileapp-prod-d6930.firebasestorage.app',
    measurementId: 'G-GT0B5PCBPW',
  );
}
