// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmyy-nprzW2tQ5wgGaWYOCIV0nyjfP5sc',
    appId: '1:867470853332:web:f78268cb448076841c6741',
    messagingSenderId: '867470853332',
    projectId: 'neocaresmileapp-dev',
    authDomain: 'neocaresmileapp-dev.firebaseapp.com',
    storageBucket: 'neocaresmileapp-dev.appspot.com',
    measurementId: 'G-0SR489CY5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3EBkSkpJxZIX6fKZtqjEGgXTXCirfcZo',
    appId: '1:867470853332:android:c1f75c199e96b3cc1c6741',
    messagingSenderId: '867470853332',
    projectId: 'neocaresmileapp-dev',
    storageBucket: 'neocaresmileapp-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr2Om6z_yRoeWZQ0h8VECrdQYRCT_M8ss',
    appId: '1:867470853332:ios:58da6a24e55943c91c6741',
    messagingSenderId: '867470853332',
    projectId: 'neocaresmileapp-dev',
    storageBucket: 'neocaresmileapp-dev.appspot.com',
    iosBundleId: 'com.example.neocaresmileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr2Om6z_yRoeWZQ0h8VECrdQYRCT_M8ss',
    appId: '1:867470853332:ios:58da6a24e55943c91c6741',
    messagingSenderId: '867470853332',
    projectId: 'neocaresmileapp-dev',
    storageBucket: 'neocaresmileapp-dev.appspot.com',
    iosBundleId: 'com.example.neocaresmileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmyy-nprzW2tQ5wgGaWYOCIV0nyjfP5sc',
    appId: '1:867470853332:web:729992158e9be4df1c6741',
    messagingSenderId: '867470853332',
    projectId: 'neocaresmileapp-dev',
    authDomain: 'neocaresmileapp-dev.firebaseapp.com',
    storageBucket: 'neocaresmileapp-dev.appspot.com',
    measurementId: 'G-BX79SXZ6J3',
  );

}